services:
  - type: web
    name: mansati-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mansati-db
          property: connectionString
      - key: PORT
        value: 10000
    autoDeploy: true

databases:
  - name: mansati-db
    plan: free
